### ISSUE TITLE
[Bug] Doesn't open on Windows 10

### ISSUE THREAD

**Issue by marcusturewicz** [DotPurpleApp/DotPurple-App#1]
**Describe the bug**
The app doesn't open on Windows.

**To Reproduce**
1. Install on Windows
2. Click on DotPurple icon in start menu
3. Nothing happens

**Expected behavior**
DotPurple should open and I can load a project etc

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1909

**Additional context**

**Comment by Deadpikle** [comment]
Hey @marcusturewicz! Sorry you're having issues. I'm running the same version of Windows, so I'm not immediately sure what the issue is. Could you do me a favor and do a few things for me so we can figure out what's going on?

* Check Event Viewer -> Windows Logs -> Application. Does anything show up there for DotPurple that would be helpful?
* Can you look in `%appdata%/DotPurple` (`C:/Users/[username]/AppData/Roaming/DotPurple`) and see if there are any crashes in a `crashes` folder in there? The crash reporter is the first thing that runs, so it's a little odd that even that isn't showing up. If there are any crashes there, could you please upload them here for us?
* Is .NET 4.8 installed on your computer?
* Do you have the .NET Core 3 SDK installed on your computer? (Any clue which version? `dotnet --list-runtimes` should help.)
* Can you check Task Manager and make sure DotPurple shows up there in the first place?

Thanks! Again, sorry things aren't working right. We do what we can, but there are always issues somewhere. :)

If the above doesn't work out, we can work on sending you some debug builds or something to figure out what's going on.

**Comment by marcusturewicz** [comment]
Sure thing:

- There are two errors that show up in Event Viewer:

```
Level	Date and Time	Source	Event ID	Task Category
Error	16/06/2020 11:03:51 AM	.NET Runtime	1026	None	Application: DotPurple.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.BadImageFormatException

Exception Info: System.BadImageFormatException
   at System.Reflection.RuntimeAssembly.nLoadImage(Byte[], Byte[], System.Security.Policy.Evidence, System.Threading.StackCrawlMark ByRef, Boolean, Boolean, System.Security.SecurityContextSource)
   at System.Reflection.Assembly.Load(Byte[])
   at <Module>.⁬​‭⁫‫‌⁭‬​‎‪‎‫⁫‍​⁮‬⁬⁫‫‏‍‎‍‍‮⁪⁪​‬⁪⁫​⁯⁬‫‌⁯⁯‮()
   at <Module>..cctor()

Exception Info: System.TypeInitializationException
```

```
Level	Date and Time	Source	Event ID	Task Category
Error	16/06/2020 11:03:51 AM	Application Error	1000	(100)	"Faulting application name: DotPurple.exe, version: 1.0.3.1, time stamp: 0xfcaba473
Faulting module name: KERNELBASE.dll, version: 10.0.18362.693, time stamp: 0x4ba7187d
Exception code: 0xe0434352
Fault offset: 0x00114192
Faulting process id: 0x3524
Faulting application start time: 0x01d64379ff3c4143
Faulting application path: C:\Program Files\DotPurple\DotPurple.exe
Faulting module path: C:\windows\System32\KERNELBASE.dll
Report Id: 1441f7a9-ece1-4e47-bf92-fe910578a90c
Faulting package full name: 
Faulting package-relative application ID: "
```

- The folder `%appdata%\DotPurple` does not exist.

- .NET 4.8 is not installed

- I have .NET Core 3.1:

```
Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

- DotPurple shows up for a second in Task Manager, then disappears

All good, no worries! Just interested to try this out.

**Comment by Deadpikle** [comment]
Hm, well, that's something to look into. 🤔 I will take a look at this tomorrow and probably post some debug builds here to try. Thanks for the info! I appreciate it.

**Comment by Deadpikle** [comment]
Wait, .NET Framework 4.8 isn't installed? Can you try installing that? The installer *should* have grabbed it for you, and the program should have told you if that wasn't installed, but...the app depends on it.

(I'll look into the other issues tomorrow. Seems like something is afoot.)

**Comment by marcusturewicz** [comment]
Actually, .NET Framework 4.8 is installed, my bad. I couldn't find it in `Add or Remove Programs`, but I checked via registry and it is there.

**Comment by Deadpikle** [comment]
Working on this now. I'll have some test builds up shortly to help diagnose it. Are you on x86 or x64? Is your copy of Windows in English? Just realized there are some extra resource DLLs that we aren't shipping, and that could be part of the problem.

**Comment by Deadpikle** [comment]
Alright. Can you please try out the following? Please uninstall the old app before you try these.

1. https://dotpurple.io/download/windows/Install%20DotPurple%201.0.3.1-ResourceDirs.exe -- runs the app as a console (hopefully will throw a better stack trace in the console) and contains resource dirs that the initial release didn't have
2. https://dotpurple.io/download/windows/Install%20DotPurple%201.0.3.1-MiscChanges.exe -- contains some misc changes that may fix the issue
3. https://dotpurple.io/download/windows/dotpurplenetcore.7z -- .NET Core 3.1, self contained. There are a few reasons why I don't want to use .NET Core 3.1 quite yet (notably, publish trimmed doesn't work...), but it's worth trying. Uses 7z compression (https://www.7-zip.org/).

Thanks for working with me on this!

**Comment by marcusturewicz** [comment]
I'm on a x64 machine, English.

All three versions work.

**Comment by Deadpikle** [comment]
Ahhhhh ok. I'm a little confused TBH, but at least things work 😅. It's probably something to do with [redacted], but I don't want to change that yet. I'll roll out a version like #1 above and ping you again here when it's uploaded. 

Thanks for checking those. Again, really appreciate your time and patience as we get this sorted out.

**Comment by Deadpikle** [comment]
It's up! You can either use the in-app software updater or re-download from https://dotpurple.io/download/windows. Thank you!

**Comment by marcusturewicz** [comment]
Thanks, but Installed the new one, getting the following errors:

```
Faulting application name: DotPurple.exe, version: 1.0.4.0, time stamp: 0xa00ca1b3
Faulting module name: KERNELBASE.dll, version: 10.0.18362.693, time stamp: 0xf1894a25
Exception code: 0xe0434352
Fault offset: 0x000000000003a859
Faulting process id: 0xf84
Faulting application start time: 0x01d64440ec69edce
Faulting application path: C:\Program Files\DotPurple\DotPurple.exe
Faulting module path: C:\windows\System32\KERNELBASE.dll
Report Id: 8322e4a2-f6e5-43fc-bff7-94321ff6e2a6
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Application: DotPurple.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code e0434352, exception address 00007FFB01C7A859
Stack:
```

No crashes found in `crashes` folder.

**Comment by Deadpikle** [comment]
Huh.

Can you try https://dotpurple.io/download/windows/Install%20DotPurple%201.0.4.1.exe, please?

If that works, I'll try putting out a 1.0.4.2 via the auto-update to ensure that the change fixes things.

**Comment by marcusturewicz** [comment]
Works!

![image](https://user-images.githubusercontent.com/24448509/84844247-4c960980-b08d-11ea-9b4e-e87adda21526.png)

**Comment by Deadpikle** [comment]
That's great news!

Here's the bad news: I rebuilt a 1.0.4.2, and now _I_ am getting the issue. Created a second 1.0.4.2 installer, and that _doesn't_ have the issue. Researching more...

**Comment by Deadpikle** [comment]
Alright. I seem to have narrowed the possibility down to an old `obj` file that wasn't being deleted. See also https://stackoverflow.com/questions/3351332/system-io-ioexception-in-presentationframework-dll-on-instantiation-of-a-user-co.

If you wouldn't mind verifying one more file on your end since your computer seems to like finding the problems the fastest? :P   https://dotpurple.io/download/windows/Install%20DotPurple%201.0.4.2.exe

(1.0.4.1 download still available if the above is broken.)

**Comment by marcusturewicz** [comment]
Yep all good!

![image](https://user-images.githubusercontent.com/24448509/84872341-1eccb700-b0c5-11ea-9930-2e748b6ec051.png)

**Comment by Deadpikle** [comment]
Alright, awesome. Again, really appreciate your willingness to help here. I hope the issue is solved for good, now.

(Can't believe we didn't run into this until now...if it truly was a renaming issue, I did that _months_ ago! 😅)
