### ISSUE TITLE
Allow Your Projects pane to be resized

### ISSUE THREAD

**Issue by wjk** [DotPurpleApp/DotPurple-App#3]
This pane has a fixed width and cannot be resized, unlike the Terminal pane at the bottom. When you're using solutions with long project file names, this becomes annoying as you have to sideways-scroll all the time to see the full project names. (It's even worse on Windows or Linux, as those platforms don’t do horizontal scrolling nearly as well as macOS does.) This change will also be useful for developers with very large screens, because they can make their windows quite large, and they might want the project list to have a width that is proportional to the window size, not a very narrow fixed size.

You should need to implement limits on how far you would be able to make this pane, however, or your editor UI to the right would be broken by being squished into a smaller space than it was designed for. My rule of thumb is that resizable sidebars can be between one-fifth and one-third of the container’s width, and this value is scaled to keep the fraction constant when the window is resized. (macOS’s `NSScrollView` does this second part for me automatically.)

**Comment by Deadpikle** [comment]
Hi @wjk! Thanks for the great suggestion and for some ideas for making sure the project pane doesn't become too large.

This feature will be available in the next version of the software for all platforms. See below GIF for this working on Windows! I will close this issue when the feature has been pushed live.

![resize](https://user-images.githubusercontent.com/5092399/107590542-5b11d200-6bd6-11eb-9b11-cbc0dbbee3aa.gif)

**Comment by Deadpikle** [comment]
Closing as this feature as now been released.
