### ISSUE TITLE
Project status in 2024?

### ISSUE THREAD

**Issue by alastairlundy** [DotPurpleApp/DotPurple-App#7]
Hi there,
I was checking out DotPurple website and asset repo.

It doesn't look like DotPurple is really still being maintained and so I wanted to ask:
Is it still being maintained and are there any long term plans for this project?

Thanks,

**Comment by Deadpikle** [comment]
Hi @alastairlundy,

We are still maintaining the software. Our last bugfix was [fixed and rolled out the day after it was reported](https://twitter.com/stnluu/status/1820925746405159165). Another version will be rolled out here in the next couple months or so for .NET 9 compatibility; if you look at our changelog history, you'll see that this is what we have done the last several years.

This repo is only for bugfixes and feedback, so this repo is not a reflection of our activity.

Frankly, the software was not popular in terms of sales, and like many companies, what is not popular is not updated as often. When our store was up, we did not get many sales. However, the software still covers nearly all your basic needs (and more) for the .NET CLI, so in that sense, we aren't fixing what isn't broken.

So, we keep the lights on and working and fix bugs for those that want to use it. The software is free right now while our store is down, so feel free to make use of all features, enjoy the software, and let us know if you have feedback.

Thanks! :-)

**Comment by alastairlundy** [comment]
> We are still maintaining the software. Our last bugfix was [fixed and rolled out the day after it was reported](https://twitter.com/stnluu/status/1820925746405159165). Another version will be rolled out here in the next couple months or so for .NET 9 compatibility; if you look at our changelog history, you'll see that this is what we have done the last several years.

Thanks for the clarification. From what I could see before creating this issue, the most recent update on the windows version was from almost a year ago and it seemed like support was quietly ending or being cut off.

I think it might be worth pinning this issue in the issues section to show that the project is still being maintained.

> This repo is only for bugfixes and feedback, so this repo is not a reflection of our activity.
That's totally fair, though the levels of interaction through bug fixes and feedback can be an indicator of the status of a project.

> Frankly, the software was not popular in terms of sales, and like many companies, what is not popular is not updated as often. When our store was up, we did not get many sales.
If I could offer some suggestions, I think you should charge a lot more money for the paid plans (doubling or even tripling the price would not be uncalled for). and switch the Pro individual purchase to provide 1 year of support instead of being perpetual for new customers.

Just my 2 cents though.

> So, we keep the lights on and working and fix bugs for those that want to use it. The software is free right now while our store is down, so feel free to make use of all features, enjoy the software, and let us know if you have feedback.

Cool. Thanks for making this program.
